### ISSUE TITLE
Part 1 Step 14 should indicate that only data from OBD Modules needs to be stored 

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#490]

**Comment by ericthomasswenson** [comment]
I don’t expect anyone to object to adding OBD in front of ECU.  
The user bears the responsibility for use of the test where test expectations are not met.
This is related to the OBD compliance = 00h problem too.  
I can also say we can add fail if data provided by non OBD ecu in the plurality of cases, but shan’t: it hasn’t been needed.
This would not be good way to inform me of design decisions after the fact.

**Comment by mmschaefer** [comment]
I am confused.  Currently, the spec says:
6.1.14.1 Actions
a. Global DM26 [(send Request (PGNPG 59904) for PGNPG 64952 (SPNSPs 3301-3305)]). 
i. Create list by ECU address of all data and current status for use later in the test.
b. Display monitor readiness composite value in log for OBD ECU replies only.

Are we going to update the document to say "save only the OBD ECUs"?  Later in the testing, we only use the OBD module info so, for clarity, it might help to call that out here.

**Comment by ericthomasswenson** [comment]
By definition in SAE J1939-73, any DM26 data received is OBD data.

It should come only from an OBD ECU, but that isn’t in the failure criteria, which are intended to focus on likely failures first (a heuristic approach to be sure).  There is the general requirement to provide a warning for any response that was not received from an OBD module.

Creating a list of the received responses will suffice. Time since ... is usually checked for accuracy to the second from the baselines like this one.  Number of engine starts is checked too.  An extra response would be checked alongside the expected response(s).

_6.1.14.1 Fail criteria: **(paste was incomplete from Adobe ... refer to text for complete content)**
a. Fail if any response for any monitor supported in DM5 by a given ECU is reported as '0=monitor  complete this cycle or not supported' in SPN 3303 bits 1-4 and SPN 3305 [except comprehensive components monitor (CCM)]. 
b. Fail if any response for each monitor not supported in DM5 by a  given  ECU  is  not  also  reported  in DM26 as '0=monitor complete this cycle or not supported' in SPN 3303 bits 5-7 or not  supported' in SPN 3303 bits 1 - 4.
c. Fail  if  any response  from 2  and  SPN 3304.[20] an ECU  indicating  support for CCM monitor in  DM5  reports  '0=monitor disabled for rest of this cycle or not supported' in SPN 3303 bit 3.   
d. Fail if any response indicates number of warm ups since code clear  (WUSCC) (SPN 3302) is  not zero.
e. Fail if any response indicates  time since engine start (SPN  3301)  is  not  zero. 
f. Fail if no OBD ECU provides DM26._

**Comment by ericthomasswenson** [comment]
No changes to the text are believed to be required in this case, unless only data from OBD modules was saved.

**Comment by gumbelmj** [comment]
The current design on preserves responses from OBD modules, though it will display any responses it receives from non-OBD modules.

**Comment by ericthomasswenson** [comment]
In that case let’s add OBD in front of ECU

_6.1.14.1 Actions
a. Global DM26 [(send Request (PG 59904) for PG 64952 (SPs 3301-3305)]).
`i.` Create list by **OBD** ECU address of all data and current status for use later in the test.
b. Display monitor readiness composite value in log for OBD ECU replies only._

**Comment by ericthomasswenson** [comment]
Changes from SPN to SP and PGN to PG in the recent text are intended to strictly editorial, to meet new terminology conventions for the ballot. No technical are intended.

**Comment by ericthomasswenson** [comment]
OBD inserted in front of ECU for 6.1.14.1.a.i

i.	Create list by OBD ECU address of all data and current status for use later in the test.

**Comment by ericthomasswenson** [comment]
OBD was added for 2/25/2021 draft
