### ISSUE TITLE
Part 1 Step 26 Document which SPNs are to be excluded/skipped

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#511]
#509 & #510 are enhancements to not check for certain SPNs.  This needs to be memorialized in changes to /84.

**Comment by ericthomasswenson** [comment]
Text will be amended to include the list prepared below.

Please create an exclusion list Part 1 test 26 for SPNs 
(588, 1213, 1220, 12675, 12730, 12783, 12797).
PGs that map to these tests shall be omitted from the list of PGs that are considered for the broadcast and on request sections of the test.  The test shall provide evidence of their omission by their exclusion in the list of subject PGs and SPs that was created to improve the transparency of test 26, as shown in the example below.

**Comment by ericthomasswenson** [comment]
(h)(4.2.2)(C) motivates the inclusion of SPs 1213 and 1220 in DM24 when it mentions them as required communications elements:

(C) Number of stored confirmed/MIL-on fault codes, monitor status (i.e., disabled for the rest of this driving cycle, complete this driving cycle, or not complete this driving cycle) since last engine shut-off for each monitor used for readiness status, distance traveled (or engine run time for engines not utilizing vehicle speed information) while MIL activated, distance traveled (or engine run time for engines not utilizing vehicle speed information) since fault memory last cleared, number of warm-up cycles since fault memory last cleared, **_OBD requirements to which the engine is certified (e.g., California OBD, California OBD-child rating (i.e., for engines subject to (d)(7.1.2) or (d)(7.2.3)) EPA OBD, European OBD, non-OBD), MIL status (i.e., commanded-on or commanded-off)_**;

It is therefore understandable that they would be included in DM24, even if not needed for test results or freeze frame.

**Comment by ericthomasswenson** [comment]
For test 6.1.26, clarify and enhance Actions1 et. al.

6.1.26 Data stream support verification
_6.1.26.1 Actions:
**a. Create a list of expected SPNs and PGNs from the DM24 response, where the data stream support bit defined in SAE J1939-73 5.7.24 is 0. Omit the the following SPNs (588, 1213, 1220, 12675, 12730, 12783, 12797) which are included in the list. Display the completed list noting those omitted SPNs and supported SPNs as ‘broadcast’ or ‘upon request’.**
b. Gather broadcast data for all SPNs that are supported for data stream in the OBD ECU DM24 responses.
c. Gather/timestamp each parameter that is observed at least three times to be able to verify frequency of broadcast._

_6.1.26.2 Fail/warn criteria: 
a. Fail if no response/no valid data for any broadcast SPN indicated as supported by the OBD ECU in DM24. 23 
b. Fail if any parameter is not broadcast within ± 10% of the specified broadcast period.24  
c. Fail/warn if any broadcast data is not valid for KOEO conditions as per Table A-1, Minimum Data Stream Support.25 
d. Fail/warn per Table A-1, if an expected SPN from the DM24 support list is provided by a non-OBD ECU. 
e. Fail/warn per Table A-1 if two or more ECUs provide an SPN listed in Table A-1._

**Comment by ericthomasswenson** [comment]
See #525 for follow on effort for On request Table A-1 SPNs that were not included in DM24.

**Comment by gumbelmj** [comment]
Closing to merge with #525

**Comment by ericthomasswenson** [comment]
a. Create a list of expected SPNs and PGNs from the DM24 response, where the data stream support bit defined in SAE J1939-73 5.7.24 is 0. Omit the the following SPNs (588, 1213, 1220, 12675, 12730, 12783, 12797) which are included in the list. Display the completed list noting those omitted SPNs and supported SPNs as ‘broadcast’ or ‘upon request’.

Added to text in 6.1.26.1

**Comment by ericthomasswenson** [comment]
a. Create a list of expected SPNs and PGNs from the DM24 response, where the data stream support bit defined in SAE J1939-73 5.7.24 is 0. Omit the the following SPNs (588, 1213, 1220, 12675, 12730, 12783, 12797) which are included in the list. Display the completed list noting those omitted SPNs and supported SPNs as ‘broadcast’ or ‘upon request’.

Added to text in 6.1.26.1
